version: '3.8'
services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - "3000:3000"
    depends_on:
      - rhiza-api
      - rhiza-ui
    restart: unless-stopped

  rhiza-api:
    build: ./rhiza-api
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_BEARER_TOKEN_BEDROCK=${AWS_BEARER_TOKEN_BEDROCK:-}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}
    depends_on:
      - neo4j
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

  rhiza-ui:
    build: ./rhiza-ui
    ports:
      - "8081:8080"
    depends_on:
      - rhiza-api
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /var/cache/nginx
      - /var/run

  neo4j:
    image: neo4j:5.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
